// <auto-generated />
using ECom.Services.Balance.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECom.Services.Balance.Infrastructure.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20220504104025_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ECom.Services.Balance.Domain.AggregateModels.UserAggregate.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("Credit_Limit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("User_Name");

                    b.HasKey("Id");

                    b.ToTable("userbalance", "Balance");
                });

            modelBuilder.Entity("ECom.Services.Balance.Infrastructure.KafkaOffset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("CommandOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("Command_Offset");

                    b.Property<long>("PersistentOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("Persistent_Offset");

                    b.HasKey("Id");

                    b.ToTable("kafkaoffset", "Balance");
                });
#pragma warning restore 612, 618
        }
    }
}
